id: node_benefits
learningObjectives:
  - Evaluate the primary benefits of using Node.js.
hints:
  - Consider Node.js's non-blocking architecture.
  - Its speed and scalability are well-known benefits.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Awesome work so far! Time for a quick question: Why is Node.js beneficial
              for web development? Pick the best answer that highlights its
              advantages!"
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - Node.js is event-driven and supports many simultaneous connections.
          - Node.js can only run JavaScript on the frontend.
          - Node.js is only useful for small applications.
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Correct! Node.js's event-driven, non-blocking architecture is perfect for
                      handling numerous simultaneous connections efficiently.
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Not quite. Node.js allows JavaScript to run server-side, which is one of
                      its key strengths!
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Nope, Node.js is scalable and suitable for apps of all sizes. Try again!
            - actionId: replay_action
              params:
                actionName: quiz
